config/routes.rb
Rails.application.routes.draw do

  resources :transactions
  # devise_for :admins
  
  # match ':controller(/:action(/:id))', :via => [:get, :post]
  # get 'static_pages/home'
  # get 'static_pages/about'
  # get 'static_pages/contact'
  # get 'static_pages/news'
  
  root 'static_pages#home'
  get  '/news',    to: 'static_pages#news'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get  '/userlist', to: 'authentication#index'

  # match '/authentication/update/:id', to: 'authentication#update', via: :post


  # resources :account
  get   '/account', to: 'account#index'
  get   '/account/:id/show', to: 'account#show'
  get   '/account/all', to: 'account#all_index'
  
  get   '/account/new', to: 'account#new'
  post   '/account', to: 'account#create'
  get   '/account/:id/edit', to: 'account#edit'
  post   '/account/:id', to: 'account#update'

  get    '/transactions/fund-transfer/new', to: 'transactions#fund_transfer'
  post    '/transactions/fund-transfer', to: 'transactions#transfer'
  get     'transactions/paybill/new',   to: 'transactions#paybill'
  post    'transactions/paybill',       to: 'transactions#pay'

  get     '/transactions/cash-withdraw/new', to: 'transactions#cash_withdraw'
  post    '/transactions/cash-withdraw', to: 'transactions#withdraw'
  get     '/transactions/cash-deposit/new', to: 'transactions#cash_deposit'
  post    '/transactions/cash-deposit', to: 'transactions#deposit'

  get     '/transactions/income/new', to: 'transactions#income'
  post    '/transactions/income', to: 'transactions#create_income'
  get     '/transactions/expenses/new', to: 'transactions#expenses'
  post    '/transactions/expenses', to: 'transactions#create_expenses'

  get   '/transactions/:id/auth', to: 'transactions#auth', as: 'auth'
  post   '/transactions/:id', to: 'transactions#authorise'
  
  get '/unau_transactions', to: 'transactions#unau_list'  

  get '/users', to: 'users/session#index'
  get   '/unau_show/:id', to: 'transactions#unau_show'
  
  get 'audit/detail', to: 'audit#detail'
  get 'audit/index'
  get 'interest', to: 'interest#index'
  get 'interest/show'
  

  # devise_for :admins, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  devise_for :admins, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }


# devise_for :users, path: "", 
#   controllers: 
#   { 
#     sessions: "sessions", 
#     registrations: "registrations" 
#   }, 
#   path_names: 
#   { 
#     sign_in: 'login', 
#     password: 'forgot', 
#     confirmation: 'confirm', 
#     unlock: 'unblock', 
#     sign_up: 'register', 
#     sign_out: 'signout'
#   }

  # get  'new', to: 'admins/registrations#new'
  #   edit_admin_registration GET    /admins/edit(.:format)          devise/registrations#edit
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]


  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.where(status: 'Auth', created_by: current_user.username)
  end

  # GET /transactions
  # GET /transactions.json
  def unau_list
    @transactions = Transaction.where(status: 'Unau')
  end


  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  def unau_show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.created_by = current_user.username

    valid = validate_input(@transaction, transaction_params)
    save valid, 'show', 'new'
  end

  # for users to pay bill online
  def paybill
    @transaction = Transaction.new
  end

  def pay
    amount = transaction_params[:debit_amount]
    @transaction = Transaction.new(transaction_params.merge(:credit_account=> '6', :credit_amount=> amount,
      :created_by=>current_user.username, :status=>'Auth', :authorised_by=>current_user.username, :authorised_date=>Time.now))

    valid = validate_input(@transaction, transaction_params)
    # save valid, 'show', 'paybill'
    save valid, 'show', 'paybill', true
  end

  # for users to transfer money online
  def fund_transfer
    @transaction = Transaction.new
  end


  def transfer
    amount = transaction_params[:debit_amount]
    @transaction = Transaction.new(transaction_params.merge(:credit_amount=> amount,
      :created_by=>current_user.username, :status=>'Auth', :authorised_by=>current_user.username, :authorised_date=>Time.now))
    #@transaction.attributes(:transaction_type => 0)
    valid = validate_input(@transaction, transaction_params)
    # save valid, 'show', 'fund_transfer'
    save valid, 'show', 'fund_transfer', true
  end

  # perform cash withdrawal transaction
  def cash_withdraw
    @transaction = Transaction.new()
  end

  def withdraw
    amount = transaction_params[:debit_amount]
    @transaction = Transaction.new(transaction_params.merge(:credit_account=>2, :credit_amount=> amount, :created_by=>current_user.username))

    valid = validate_input(@transaction, transaction_params)

    save valid, 'show', 'cash_withdraw', false
  end

  def cash_deposit
    @transaction = Transaction.new()
  end

  def deposit
    amount = transaction_params[:credit_amount]
    @transaction = Transaction.new(transaction_params.merge(:debit_account=>1, :debit_amount=> amount, :created_by=>current_user.username))

    valid = validate_input(@transaction, transaction_params)

    save valid, 'show', 'cash_deposit', false
  end

  # GET /transactions/1/edit
  def edit
    @transactions = Transaction.find(params[:id])
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    valid = validate_input(@transaction, params)

    if not valid.nil?
      flash[:notice] = valid
      render :action=>'edit'
    elsif @transaction.update(transaction_params)
      flash[:notice] = 'Transaction was successfully updated.'
      render :action=>'show'
    else
      flash[:notice] = 'Error: unable to save the record!'
      render :action=>'edit'
    end
  end

  def income
    @transaction = Transaction.new
  end

  def create_income
    amount = transaction_params[:credit_amount]
    @transaction = Transaction.new(transaction_params.merge(
      :debit_account=> 1, :debit_amount=>amount, :credit_account=> 3, :created_by=>current_user.username))

    valid = validate_input(@transaction, transaction_params)
    save valid, 'show', 'income', false
  end

  def expenses
    @transaction = Transaction.new
  end

  def create_expenses
    amount = transaction_params[:debit_amount]
    @transaction = Transaction.new(transaction_params.merge(
      :credit_account=>2, :credit_amount=>amount, :debit_account=> 4, :created_by=>current_user.username))

    valid = validate_input(@transaction, transaction_params)
    save valid, 'show', 'expenses', false
  end

  def auth
    @transaction = Transaction.find(params[:id])
    @transaction.status = "Auth"
    @transaction.authorised_by = current_user.username
    @transaction.authorised_date = Time.now
  end 

  def authorise
    @transaction = Transaction.find(params[:id])
    puts auth_params[:authorised_by]
    puts auth_params[:authorised_date]

    if not authorise_transaction @transaction   # authorise the transaction
      flash[:notice] = 'Unable to authorise the transaction due to insufficient balance.'
      render :action=>'auth'
    else
      if @transaction.update({ :status => auth_params[:status], :authorised_by => auth_params[:authorised_by], :authorised_date => auth_params[:authorised_date] })
        flash[:notice] = 'Transaction was successfully authorised.'
        render :action=>'show'
      else
        flash[:notice] = 'Error: unable to authorise the record!' 
        render :action=>'edit'
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    if @transaction.status == "Unau"
      @transaction.destroy  
      respond_to do |format|
        format.html { redirect_to unau_transactions_url, notice: 'Transaction was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:notice] = 'Transaction was not destroyed.'
      render :action=>'index '
    end 
  end

  private
    # update relevant accounts for a transaction for staff
    def transact transaction
      dr_acc = transaction.debit_account
      dr_amt = transaction.debit_amount*(-1)
      cr_acc = transaction.credit_account
      cr_amt = transaction.credit_amount

      if not update_working_balance dr_acc, dr_amt
        puts "failed ---------------------- "
        return false
      end
      update_working_balance cr_acc, cr_amt
      
      return true
    end

    # update relevant accounts for online transactions
    def online_transact transaction
      dr_acc = transaction.debit_account
      dr_amt = transaction.debit_amount
      cr_acc = transaction.credit_account
      cr_amt = transaction.credit_amount

      dr_account = Account.find(dr_acc)
      cr_account = Account.find(cr_acc)

      dr_account.working_balance -= dr_amt
      dr_account.actual_balance -= dr_amt
      dr_account.last_debit = dr_amt

      cr_account.working_balance += cr_amt
      cr_account.actual_balance += cr_amt
      cr_account.last_debit = cr_amt
      
      balance_status = (dr_account.working_balance < 0 or dr_account.actual_balance < 0)
      puts "debit_amount----------------- " + dr_amt.to_s
      puts "working_balance----------------- " + dr_account.working_balance.to_s
      puts "working_balance----------------- " + (dr_account.working_balance < 0).to_s
      puts "actual_balance----------------- " + dr_account.actual_balance.to_s
      puts "actual_balance----------------- " + (dr_account.actual_balance < 0).to_s
      puts "balance_status----------------- " + balance_status.to_s
      puts "type----------------- " + ["saving", "fix_deposit", "current"].include?(dr_account.account_type).to_s

      if (["saving", "fix_deposit", "current"].include?(dr_account.account_type) and balance_status)
        return false
      end
      
      dr_account.save
      cr_account.save

      return true
    end

    # update working balance for a transaction
    def update_working_balance account_number, transaction_amount
      account = Account.find(account_number)
      account.working_balance += transaction_amount

      if (["saving", "fix_deposit", "current"].include?(account.account_type) and (account.working_balance < 0))
        return false
      else
        account.save
      end

      return true
    end

    # update actual balance of the relevant accounts when a transaction is authorised
    def authorise_transaction transaction
      if not update_dr_acc_bal(transaction.debit_account, transaction.debit_amount)
        return false
      end
      update_cr_acc_bal transaction.credit_account, transaction.credit_amount

      return true
    end

    # update actual account balance and last debit transaction amount
    def update_dr_acc_bal account_number, transaction_amount
      account = Account.find(account_number)
      account.actual_balance -= transaction_amount
      account.last_debit = transaction_amount

      if (["saving", "fix_deposit", "current"].include?(account.account_type) and (account.actual_balance < 0))
        return false
      else
        account.save
      end
      return true
      # account.save
      # puts "account working balance --------------- " + account.actual_balance.to_s
    end

    # update actual account balance and last credit transaction amount
    def update_cr_acc_bal account_number, transaction_amount
      account = Account.find(account_number)
      account.actual_balance += transaction_amount
      account.last_credit = transaction_amount
      account.save
      # puts "account working balance --------------- " + account.actual_balance.to_s
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:debit_account, :credit_account, :debit_amount, :credit_amount, 
        :effective_date, :transaction_type, :created_by, :working_balance, :actual_balance, :external_ref)
    end

    def auth_params
      params.permit(:status, :authorised_by, :authorised_date)
    end

    # validate input
    def validate_input transaction, txn_params
    # query up if account has the existing account number
      debit = Account.find_by_id(transaction.debit_account)

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  
  <div class="field">
    <%= f.label :debit_account %>
    <%= f.text_field :debit_account %>
  </div>

  <div class="field">
    <%= f.label :debit_amount %>
    <%= f.text_field :debit_amount %>
  </div>

  <div class="field">
    <%= f.label :transaction_type %>
    <%= f.text_field :transaction_type %>
  </div>

  <div class="field">
    <%= f.label :credit_account %>
    <%= f.text_field :credit_account %>
  </div>
<!--
  <div class="field">
    <%= f.label :credit_amount %>
    <%= f.text_field :credit_amount %>
  </div>
-->
  <div class="field">
    <%= f.label :effective_date %>
    <%= f.text_field :effective_date %>
  </div>
<!--
  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :created_by %>
    <%= f.text_field :created_by %>
  </div>

  <div class="field">
    <%= f.label :authorised_by %>
    <%= f.text_field :authorised_by %>
  </div>

  <div class="field">
    <%= f.label :created_at %>
    <%= f.text_field :created_at %>
  </div>

  <div class="field">
    <%= f.label :authorised_date %>
    <%= f.text_field :authorised_date %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/auth.html.erb
<%#= form_for(@transaction) do |f| %>
<%= form_for(:transaction, :url => {:controller => 'transactions', :action => 'authorise', :id => @transaction.id}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  <p>
  <strong>Debit Account:</strong>
    <%= f.text_field :debit_account, disabled: true %>
    <%= hidden_field_tag :debit_account, @transaction.debit_account %>
  </p>

  <p>
    <strong>Debit Amount:</strong>
    <%= f.text_field :debit_amount, disabled: true %>
  </p>

  <p>
    <strong>Transaction Type:</strong>
    <%= f.text_field :transaction_type, disabled: true %>
  </p>

  <p>
    <strong>Credit Account:</strong>
    <%= f.text_field :credit_account, disabled: true %>
  </p>

  <p>
    <strong>Credit Amount:</strong>
    <%= f.text_field :credit_amount, disabled: true %>
  </p>

  <p>
    <strong>Effective Date:</strong>
    <%= f.text_field :effective_date, disabled: true %>
  </p>

  <p>
    <strong>Record status:</strong>
    <%= f.text_field :status, disabled: true %>
    <%= hidden_field_tag :status, @transaction.status %>
  </p>

  <p>
    <strong>Authorised By:</strong>
    <%= f.text_field :authorised_by, disabled: true %>
    <%= hidden_field_tag :authorised_by, @transaction.authorised_by %>
  </p>

  <p>
    <strong>Authorised Date:</strong>
    <%= f.text_field :authorised_date, disabled: true %>
    <%= hidden_field_tag :authorised_date, @transaction.authorised_date %>
  </p>

  <p class="actions">
    <%= submit_tag("Authorise transaction") %>
  </p>
<% end %>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/cash_deposit.html.erb
<h2>Cash Deposit</h2>

<%= form_for(:transaction, :url => {:controller => 'transactions', :action => 'deposit'}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  <p>
  <strong>Deposit Account:</strong>
    <%= f.text_field :credit_account %>
  </p>

  <p>
  <strong>Deposit Amount:</strong>
    <%= f.text_field :credit_amount %>
  </p>

  <p class="actions">
    <%= submit_tag("Deposit") %>
  </p>
<% end %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/cash_withdraw.html.erb
<h2>Cash Withdrawal</h2>

<%= form_for(:transaction, :url => {:controller => 'transactions', :action => 'withdraw'}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  <p>
  <strong>Debit Account:</strong>
    <%= f.text_field :debit_account %>
  </p>

  <p>
  <strong>Debit Amount:</strong>
    <%= f.text_field :debit_amount %>
  </p>

  <p class="actions">
    <%= submit_tag("Withdraw") %>
  </p>
<% end %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>
<p id="notice"><%#= notice %></p>
<%= render 'form', transaction: @transaction %>

app/views/transactions/expenses.html.erb
<h2>Expenses</h2>

<%= form_for(:transaction, :url => {:controller => 'transactions', :action => 'create_expenses'}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  <p>
  <strong>Income Amount:</strong>
    <%= f.text_field :debit_amount %>
  </p>

  <p class="actions">
    <%= submit_tag("Insert Expenses") %>
  </p>
<% end %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/fund_transfer.html.erb
<%= form_for(:transaction, :url => {:controller => 'transactions', :action => 'transfer'}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  <p>
  <strong>Debit Account:</strong>
    <%= f.text_field :debit_account %>
  </p>

  <p>
  <strong>Debit Amount:</strong>
    <%= f.text_field :debit_amount %>
  </p>

  <p>
    <strong>Credit Account:</strong>
    <%= f.text_field :credit_account %>
  </p>

  <%= hidden_field_tag :trasaction_type, value: 0 %>

  <p class="actions">
    <%= submit_tag("Transfer") %>
  </p>
<% end %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/income.html.erb
<h2>Income</h2>

<%= form_for(:transaction, :url => {:controller => 'transactions', :action => 'create_income'}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  <p>
  <strong>Income Amount:</strong>
    <%= f.text_field :credit_amount %>
  </p>

  <p class="actions">
    <%= submit_tag("Insert Income") %>
  </p>
<% end %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<% if current_user.role == "customer" %>
  <%= link_to 'Fund Transfer', transactions_fund_transfer_new_path %> | <%= link_to 'Paybill', transactions_paybill_new_path %>
  <br>
<% else %>
  <%= link_to 'Unauthorised transactions', unau_transactions_path %> | <%= link_to 'Cash Deposit', transactions_cash_deposit_new_path %> | <%= link_to 'Cash Withdraw', transactions_cash_withdraw_new_path %> | <%= link_to 'Income', transactions_income_new_path %> | <%= link_to 'Expenses', transactions_expenses_new_path %> 
  <br>
  <%#= link_to 'New Transaction', new_transaction_path %>
<% end %>

<table class="table">
  <thead>
    <tr>

      <th>Txn No.</th>
      <th>Debit Account</th>
      <th>Credit Account</th>
      <th>Txn Amount</th>
      <th>Effective Date</th>
      <th colspan="4"></th>

    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>

        <td><%= transaction.id %></td>
        <td><%= transaction.debit_account %></td>
        <td><%= transaction.credit_account %></td>
        <td><%= transaction.credit_amount %></td>
        <td><%= transaction.effective_date %></td>

        <td><%= link_to 'Show', transaction %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>
<p id="notice"><%#= notice %></p>
<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/paybill.html.erb
<%= form_for(:transaction, :url => {:controller => 'transactions', :action => 'pay'}) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>
  <p>
  <strong>Debit Account:</strong>
    <%= f.text_field :debit_account %>
  </p>

  <p>
  <strong>Debit Amount:</strong>
    <%= f.text_field :debit_amount %>
    <%#= f.text_field :credit_account %>
  </p>

  <p>
    <strong>Payee Account:</strong>
    <%= f.text_field :external_ref %>
  </p>
  <%#x= f.hidden_field :credit_account, value: 6 %>
  <%= hidden_field_tag :trasaction_type, value: 0 %>

  <p class="actions">
    <%= submit_tag("Transfer") %>
  </p>
<% end %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Debit Account:</strong>
  <%= @transaction.debit_account %>
</p>

<p>
  <strong>Credit Account:</strong>
  <%= @transaction.credit_account %>
</p>

<p>
  <strong>External Reference:</strong>
  <%= @transaction.external_ref %>
</p>

<p>
<strong>Debit Amount:</strong>
  <%= @transaction.debit_amount %>
</p>

<p>
  <strong>Credit Amount:</strong>
  <%= @transaction.credit_amount %>

  <strong>Transaction Amount:</strong>
  <%= @transaction.credit_amount %>
</p>

<p>
  <strong>Effective Date:</strong>
  <%= @transaction.effective_date %>
</p>

<p>
  <strong>Record status:</strong>
  <%= @transaction.status %>

</p>
<% if @transaction.status != 'Auth' %>
  <%= link_to 'Edit', edit_transaction_path(@transaction) %>
<% end %>
<%= link_to 'Back', transactions_path %>

app/views/transactions/unau_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Unauthorised Transactions</h1>


<%= link_to 'Unauthorised transactions', unau_transactions_path %> | <%= link_to 'Cash Deposit', transactions_cash_deposit_new_path %> | <%= link_to 'Cash Withdraw', transactions_cash_withdraw_new_path %> | <%= link_to 'Income', transactions_income_new_path %> | <%= link_to 'Expenses', transactions_expenses_new_path %> 
<br>
<%#= link_to 'New Transaction', new_transaction_path %>

<table class="table table-striped">
  <thead>
    <tr>

      <th>Txn No.</th>
      <th>Debit Account</th>
      <th>Credit Account</th>
      <th>Txn Amount</th>
      <th>Effective Date</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>

        <td><%= transaction.id %></td>
        <td><%= transaction.debit_account %></td>
        <td><%= transaction.credit_account %></td>
        <td><%= transaction.credit_amount %></td>
        <td><%= transaction.effective_date %></td>

        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Authorise', auth_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/unau_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Debit Account:</strong>
  <%= @transaction.debit_account %>
</p>

<p>
  <strong>Credit Account:</strong>
  <%= @transaction.credit_account %>
</p>

<p>
<strong>Debit Amount:</strong>
  <%= @transaction.debit_amount %>
</p>

<p>
  <strong>Credit Amount:</strong>
  <%= @transaction.credit_amount %>

  <strong>Transaction Amount:</strong>
  <%= @transaction.credit_amount %>
</p>

<p>
  <strong>Effective Date:</strong>
  <%= @transaction.effective_date %>
</p>

<p>
  <strong>Record status:</strong>
  <%= @transaction.status %>

</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', unau_transactions_path %>